# ============================================================= #
# Configuration file about how we're developing the app called: #
# ============================================================= #
appname: DevotionProjectTemplate

languages: fr,de

api:
    srcdir: api
    bindir: ../bin
    config: apiconf.yaml
    port: 42042
    i18n:
        links:
            - https://sheets.googleapis.com/v4/spreadsheets/13wVHCo7x0bu4Gdtn5rEvr5OsddVEK0rzVpBbqESTpqE/values/goaldn?key=AIzaSyAFb8qAmo3Wva5cjCg5f-gQ8tNDF6D7QzE
        keysize: 48
        folder: translations
    datadir: data
    watchalso:
        - ../../open/goald
        - unknown_project

deploying:
    dir: deploy
    remoteplatform: azure
    global:
        name: glo
        params:
            resource_ns: ???
            location: ???
            identity_sub_name: ???
            management_sub_name: ???
            acr_name: ???
            acr_rg: ???
            domain_name: ???
            oauth2_scope_guid: ???
    environments:
        - name: dev
          params:
              environment_sub_name: ???
        - name: qua
          params:
              environment_sub_name: ???
        - name: prd
          params:
              environment_sub_name: ???

# native:
#     srcdir: native
#     i18n:
#         links:
#             - https://sheets.googleapis.com/v4/spreadsheets/13wVHCo7x0bu4Gdtn5rEvr5OsddVEK0rzVpBbqESTpqE/values/goaldn?key=AIzaSyAFb8qAmo3Wva5cjCg5f-gQ8tNDF6D7QzE
#         keysize: 48
#         folder: locales
#     datadir: data

# vendors:
#     - repo: github.com/aldesgroup/goaldn
#       version: latest
#       from: lib
#       to: native/src/vendor

codeswaps:
    - from: "api"
      for: ["*.mod"]
      do:
          - replace: "// replace github.com/aldesgroup/goald => ../../../open/goald"
            with: "replace github.com/aldesgroup/goald => ../../../open/goald"
            eofcom: true
    # - from: "."
    #   for: ["tailwind.config.ts"]
    #   do:
    #       - replace: '"./src/vendor/emeraldr/styles/aldes-preset"'
    #         with: '"../../emeraldr/lib/styles/aldes-preset"'
    # - from: "."
    #   for: ["*.ts", "*.tsx"]
    #   do:
    #       - replace: '"~/vendor/emeraldr"'
    #         with: '"~/../../../emeraldr/lib"'
    #       - replace: '"~/vendor/goaldr"'
    #         with: '"~/../../../goaldr/lib"'
    # - from: "../emeraldr"
    #   for: ["*.ts", "*.tsx"]
    #   do:
    #       - replace: '"~/vendor/goaldr"'
    #         with: '"~/../../../goaldr/lib"'
